### ISSUE TITLE
Support for non-embedded map data.

### ISSUE THREAD

**Issue by leebock** [Esri/shortlist-storytelling-template-js#15]
1) Feature services
2) CSV's over the web.

**Comment by Nataliya1** [comment]
I would definitely be great if the feature services were supported to drive tabs and pop-ups. Any updates on that? Has it been considered as an enhancement? If so, any time frame? Thank you.

**Comment by RupertEssinger** [comment]
Hi Nataliya. It is definitely a key enhancement on our list but we don't have a time frame for it at this point. We know it's a limitation of the current Shortlist though that we do need to enhance. - Rupert

**Comment by juliagalindo** [comment]
Yes, I also want the feature services as a active element in the shortlist. Thanks!

**Comment by mullearn** [comment]
Feature services would be much appreciated!

**Comment by RupertEssinger** [comment]
Hi. 

Here's an update: We are working on adding feature service support into the Shortlist app and will be including that in our upcoming 1.4 release of the application template which we hope to release in the next few weeks. 

The release will include:

- Support for feature services to define tabs and also for supporting clickable layers, like transit routes, study area boundaries, etc. Support for feature services will make it much easier to publish a Shortlist from points you assemble in ArcMap or ArcGIS Pro. Currently you have to either export your points as a CSV file after first adding Lat and Long fields into its attribute table, or save them as a shapefile (at which point the 254 character maximum for text fields kicks in and can truncate your descriptions). 

- Support for up to 200 places per tab. Currently the limit is 99. This is also a frequent request from authors. 

- The option to define all the tabs in a Shortlist with a single point layer. If the Shortlist finds a point layer containing a field called TAB_NAME in your web map, it will use that layer to define all the tabs, arranging the places in your layer into tabs based on the value of that field for each place, and using the order in which the tab names in that field in the table as the tab order. Using this option will simplify creating and updating Shortlists because you can drive everything from a single dataset and move places between different tabs simply by editing their TAB_NAME field.

- The places in the point layer(s) that define your tabs will now be auto-numbered in the tabs based on the order in which they are listed in your point layer's attribute table. Currently the number of each place is taken from the required NUMBER field. Auto-numbering will make it much easier to update Shortlists because if you add or delete places you no longer have to renumber all the proceeding places to reflect the change. This also matches the way that the Story Map Tour numbers points in a tour that it reads from a point layer. The NUMBER field will no longer be required. It is still supported however, so if the Shortlist finds a NUMBER field, it will use the values in that field to number the records (which ensures that the numbering in your existing Shortlists won't change if you upgrade them to 1.4). 

All the above updates should make it easier to create and manage Shortlist data and also opens up more possibilities for automating the generation of Shortlist content from GIS databases. 

There are also some bug fixes including a fix to the issue where the popup title can collide with the popup's 'Close' control, and we will provide messaging if the Shortlist can't open its web map or can't find any valid Shortlist layers inside it.

Rupert

**Comment by DrewQuartic** [comment]
@RupertEssinger That's great news. I have just been asked to add some of this functionality to a clients shortlist app but maybe I can save them a few bucks by waiting, when do you expect the 1.4 release to be available?

One other question, when you say feature services will be supported, will the release support on site ArcGIS server feature services or will it still be necessary to publish to ArcGIS online first?

**Comment by RupertEssinger** [comment]
Hi Drew. I would definitely wait and use 1.4. We hope to release it by April 20.

ArcGIS server feature services will be supported in addition to ArcGIS Online hosted feature services

**Comment by DrewQuartic** [comment]
Excellent, thank you.

**Comment by mullearn** [comment]
Great news for us as well, thanks in advance.
Arnie, CZ.

**Comment by RupertEssinger** [comment]
Hi Drew
Thanks again for your question. It reminded me to test ArcGIS Server feature services carefully and it uncovered a bug that our dev Mark has now fixed. :)

**Comment by DrewQuartic** [comment]
No worries glad you caught it. If you need a beta tester let me know.

**Comment by RupertEssinger** [comment]
Drew>Great idea. When we have a good deliverable will post here about it

**Comment by dileeparur** [comment]
Any updates on version 1.4?

**Comment by RupertEssinger** [comment]
Sorry about the delay but have not forgotten your offer to test

**Comment by DrewQuartic** [comment]
No worries and good luck.

On Thu, Apr 30, 2015 at 1:40 PM, Rupert Essinger <notifications@github.com>
wrote:

> Sorry about the delay but have not forgotten your offer to test
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/Esri/shortlist-storytelling-template-js/issues/15#issuecomment-97960257>
> .
>



-- 
thanks

Drew Dowling
(858) 405 3582

**Comment by 4minus** [comment]
I'm really interested in version 1.4 as well. I want to realease a shortlist-application to public, but we need automated update first :)

**Comment by geofinne** [comment]
@RupertEssinger, any word on an approximate release date for the new version? We need to publicly release a shortlist soon, and just need to know if we need to make our own markers for 100+ (preferably, we'd like to wait for the release, ...if we can). :). Thanks!

**Comment by RupertEssinger** [comment]
Sorry for the delay. We plan to release first week of June (next week). Will let you know here when it is available.

**Comment by 4minus** [comment]
<3

**Comment by cooney** [comment]
Installed with version 1.4/
