### ISSUE TITLE
Using data from one Tab in another Tab (question)

### ISSUE THREAD

**Issue by cblandy** [Esri/shortlist-storytelling-template-js#52]
This is more of a question than an issue.
I have added two layers to my Web Map to use as Tabs in my Storytelling app. One layer has Public Art locations. The other tab is called Cultural Corridor which contains venues. The venues are inside a polygon layer called Cultural Corridor. I basically want to know if the following is possible. How do I get Public Art locations into the Cultural Corridor tab that are inside the Cultural Corridor. Thus the Cultural Corridor tab will have Venues and Public Art locations (preferably with different colours to differentiate).
Cheers,
Cameron

**Comment by cooney** [comment]
Hi Cameron,
The best approach would be to add the public art location features that intersect within the cultural corridor to the cultural corridor layer.  In order to display the features with different colors, you would have to add some custom JavaScript code to the main.js file.  Look for the function called 'buildLayer', that would probably be your best place to customize.  

Another great resource for getting answers and information on Story Maps is the GeoNet forums that can be found here:  <https://geonet.esri.com/community/gis/web-gis/storymaps/content>
