### ISSUE TITLE
Default Popup to Details panel

### ISSUE THREAD

**Issue by cblandy** [Esri/shortlist-storytelling-template-js#57]
Was wondering if it is possible to open the popup as the details panel and not having to click on the Details link (in the default popup) to get the Details popup.

**Comment by RupertEssinger** [comment]
By default the Shortlist just displays the popup for places. You can configure it to have a Details panel too accessed via the Details link on the popup. It's not possible to just display the Details panel instead of the popup. However you could customize the popup so it contains more information or to change its format (for example:
http://apps.themagiscian.com/cm14-argentina/ ) which could give you a similar effect of a single popup containing all the info.

Also we are working on a new UI design for the Shortlist that eliminates the separate popup and Details panel, combines them into a single panel, and relocates that panel into the tab area instead of having it cover up the map.

**Comment by jbowen24** [comment]
+1
